"""
Gemini API travel assistant summary generator.
"""
import requests
import json
import os

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

def generate_travel_summary(
    origin: str,
    destination: str,
    vehicle_type: str,
    traffic_level: str,
    confidence: float,
    eta_minutes: float,
    accident_risk: str,
    aqi: int,
    temp_c: float,
    rain_mm: float,
    visibility_km: float,
    departure_time: str,
    fuel_needed_liters: float = None,
    fuel_cost_rupees: float = None,
    traffic_impact_percent: int = None,
    co2_emissions_kg: float = None,
) -> dict:
    """
    Generate a natural-language travel summary, recommendation, safety alert, weather alert,
    fuel cost insight, and sustainability insight using the Gemini API.
    """
    model = os.environ.get("GEMINI_MODEL", "gemini-1.5-flash")
    if model.startswith("models/"):
        model = model.replace("models/", "")
    
    # Correcting domain mapping to standard Google API endpoint
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={GEMINI_API_KEY}"
    
    fuel_info = ""
    tree_info = ""
    if fuel_needed_liters is not None and fuel_cost_rupees is not None:
        co2_text = f"- Estimated CO₂ Emissions: {co2_emissions_kg:.2f} kg CO₂" if co2_emissions_kg is not None else ""
        fuel_info = f"""
- Fuel Needed: {fuel_needed_liters:.2f} Liters
- Estimated Fuel Cost: ₹{fuel_cost_rupees}
- Traffic Congestion Fuel Impact: +{traffic_impact_percent}% fuel consumption due to traffic
{co2_text}
"""
    if co2_emissions_kg is not None:
        tree_days = round(co2_emissions_kg / 0.06) if co2_emissions_kg > 0 else 0
        tree_info = f"- Tree Offset Equivalent: {tree_days} Tree-Days (One mature tree would require approximately {tree_days} days to absorb the carbon emissions generated by this journey.)"

    prompt = f"""
You are YatrAI, an AI Travel Assistant for Indian road commuters.
Analyze the following travel data and generate a JSON response.

TRAVEL DATA:
- Origin: {origin}
- Destination: {destination}
- Vehicle Type: {vehicle_type}
- Traffic Level: {traffic_level}
- Traffic Congestion Confidence: {confidence:.2f}
- Estimated Travel Time: {eta_minutes:.1f} minutes
- Road Accident Risk: {accident_risk}
- Air Quality Index (AQI): {aqi}
- Destination Temperature: {temp_c:.1f}°C
- Rainfall: {rain_mm:.1f} mm
- Visibility: {visibility_km:.1f} km
- Departure Time: {departure_time}
{fuel_info}
{tree_info}

The response MUST be a valid JSON object with the following keys:
1. "summary": A concise, natural-language, professional travel summary (approx 2-3 sentences). IMPORTANT: You MUST include the tree offset equivalent environmental interpretation in this summary to raise environment awareness (specifically: "One mature tree would require approximately X days to absorb the carbon emissions generated by this journey." based on the Tree Offset Equivalent value).
2. "travel_recommendation": A practical recommendation for the route.
3. "safety_recommendation": Advice on driving style, precautions, or safety gear.
4. "weather_alert": A brief warning about rainfall or visibility if applicable, otherwise an empty string.
5. "fuel_insight": An AI-generated fuel insight. Example: "Heavy traffic is increasing fuel consumption by approximately 25% compared to free-flow conditions. Consider delaying departure or selecting an alternative route to reduce fuel costs."
6. "sustainability_insight": An AI-generated sustainability/CO₂ footprint insight. Example: "This journey is estimated to generate approximately 5.8 kg of CO₂ emissions. Heavy congestion is increasing both fuel consumption and environmental impact. Traveling outside peak hours may reduce emissions and improve travel efficiency."

IMPORTANT: Do not return any markdown tags or backticks (like ```json). Return ONLY the raw JSON string.
"""

    headers = {"Content-Type": "application/json"}
    payload = {
        "contents": [{
            "parts": [{
                "text": prompt
            }]
        }]
    }

    fallback_summary = f"Travel from {origin} to {destination} via {vehicle_type} is expected to take {eta_minutes:.1f} minutes. Traffic is {traffic_level} and road safety risk is {accident_risk}."
    if co2_emissions_kg is not None:
        tree_days = round(co2_emissions_kg / 0.06) if co2_emissions_kg > 0 else 0
        fallback_summary += f" One mature tree would require approximately {tree_days} days to absorb the carbon emissions generated by this journey."

    fallback_response = {
        "summary": fallback_summary,
        "travel_recommendation": "Plan ahead and allocate extra travel time.",
        "safety_recommendation": "Drive defensively, follow traffic rules, and wear your seatbelt/helmet.",
        "weather_alert": "Watch out for local weather conditions." if rain_mm > 0 or visibility_km < 5 else "",
        "fuel_insight": f"Heavy traffic may increase fuel consumption. Consider driving during off-peak hours to save fuel." if traffic_level in ("Heavy", "Gridlock") else "Traffic impact on fuel consumption is minimal.",
        "sustainability_insight": f"This journey is estimated to generate approximately {co2_emissions_kg:.1f} kg of CO₂ emissions. Consider carpooling or selecting alternative transit to reduce emissions." if co2_emissions_kg is not None else "Eco-friendly driving behaviors can help lower trip carbon emissions."
    }

    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=3)
        resp.raise_for_status()
        result = resp.json()
        
        # Extract text content
        text_content = result["candidates"][0]["content"]["parts"][0]["text"].strip()
        
        # Clean up any potential markdown code blocks
        if text_content.startswith("```"):
            # strip markdown lines
            lines = text_content.splitlines()
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines[-1].startswith("```"):
                lines = lines[:-1]
            text_content = "\n".join(lines).strip()
            
        data = json.loads(text_content)
        # Ensure all required keys exist
        for key in ["summary", "travel_recommendation", "safety_recommendation", "weather_alert", "fuel_insight", "sustainability_insight"]:
            if key not in data:
                data[key] = fallback_response[key]
        return data
    except Exception as e:
        print(f"[Gemini API] Error: {e}")
        return fallback_response

