"""
Sustainability Analytics Module.
Estimates the environmental impact of a trip by converting estimated fuel burned into CO₂ emissions,
categorizes environmental impact level, and generates eco-recommendations.
"""

def calculate_sustainability(
    fuel_needed_liters: float,
    distance_km: float,
    vehicle_type: str,
    congestion_level: str,
    rain_mm: float,
    visibility_km: float,
    mileage_used: float,
) -> dict:
    """
    Calculate environmental impact of a trip.
    CO₂ Emission = Fuel Used * 2.31 kg
    """
    # 1. CO₂ Emission Calculation
    co2_emission = fuel_needed_liters * 2.31

    # 2. Environmental Impact Classification
    if co2_emission <= 2.0:
        impact_level = "Low Impact"
    elif co2_emission <= 5.0:
        impact_level = "Moderate Impact"
    elif co2_emission <= 10.0:
        impact_level = "High Impact"
    else:
        impact_level = "Very High Impact"

    # 3. Traffic Fuel factor reuse to compute traffic impact
    cong_normalized = congestion_level.lower().replace("-", " ")
    if "free" in cong_normalized:
        traffic_factor = 1.00
    elif "moderate" in cong_normalized:
        traffic_factor = 1.10
    elif "heavy" in cong_normalized:
        traffic_factor = 1.25
    elif "gridlock" in cong_normalized:
        traffic_factor = 1.45
    else:
        traffic_factor = 1.10
    
    traffic_impact_percent = round((traffic_factor - 1.0) * 100)

    # 4. Weather Fuel factor reuse to compute weather impact
    if rain_mm < 1.0:
        weather_factor = 1.00
    elif rain_mm < 5.0:
        weather_factor = 1.03
    elif rain_mm < 15.0:
        weather_factor = 1.06
    else:
        weather_factor = 1.10

    if visibility_km < 2.0:
        weather_factor *= 1.05

    weather_impact_percent = round((weather_factor - 1.0) * 100)

    # 5. Tree Offset Equivalent
    # Daily Tree Absorption: 22 kg / 365 = 0.06 kg CO2/day
    tree_days = round(co2_emission / 0.06) if co2_emission > 0 else 0
    tree_offset_interpretation = f"One mature tree would require approximately {tree_days} days to absorb the carbon emissions generated by this journey."

    # 6. Eco Recommendation Engine
    recommendations = []
    
    # Traffic recommendations
    if traffic_factor >= 1.25:
        recommendations.append("Departing 30 minutes later may reduce congestion-related emissions.")
    elif traffic_factor == 1.10:
        recommendations.append("Moderate traffic is increasing fuel consumption.")
    else:
        recommendations.append("This route currently has a lower environmental impact than peak-hour travel.")
    
    # Weather recommendations
    if rain_mm >= 15.0:
        recommendations.append("Heavy rainfall is contributing to increased fuel consumption.")
    elif rain_mm >= 5.0:
        recommendations.append("Moderate rainfall increases road resistance, slightly rising fuel consumption.")
    elif rain_mm >= 1.0:
        recommendations.append("Light rain may impact driving efficiency and increase emissions.")
        
    if visibility_km < 2.0:
        recommendations.append("Low visibility reduces driving speeds and efficiency, increasing emissions.")

    eco_recommendation = " ".join(recommendations)

    return {
        "co2_emission_kg": round(co2_emission, 2),
        "environmental_impact_level": impact_level,
        "traffic_impact_percent": traffic_impact_percent,
        "weather_impact_percent": weather_impact_percent,
        "tree_days": tree_days,
        "tree_offset_interpretation": tree_offset_interpretation,
        "eco_recommendation": eco_recommendation,
        "traffic_impact_display": f"Current traffic conditions are increasing carbon emissions by approximately {traffic_impact_percent}%."
    }
